select name from sys.tables
SELECT * FROM INFORMATION_SCHEMA.TABLES where TABLE_TYPE = 'VIEW'
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
SELECT * FROM INFORMATION_SCHEMA.COLUMN_PRIVILEGES
SELECT * FROM INFORMATION_SCHEMA.TABLE_PRIVILEGES

SELECT * FROM INFORMATION_SCHEMA.VIEWS
SELECT * FROM INFORMATION_SCHEMA.VIEW_COLUMN_USAGE
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE

SELECT * FROM INFORMATION_SCHEMA.TABLES where TABLE_TYPE = 'VIEW'
SELECT * FROM INFORMATION_SCHEMA.VIEWS